---
- name: Variable and Array
  hosts: all
  become: true
  vars:

# this data could come from a database or csv file, could also set UID, GID, etc.
    users:
      dmarcus:
        uname: dmarcus
        fname: David
        lname: Marcus
        home: /home/dmarcus
        shell: /sbin/nologin

      tstewart:
        uname: tstewart
        fname: Tim
        lname: Stewart
        home: /home/tstewart
        shell: /bin/bash

  tasks:

    - name: Create user from an array
      # check the ansible-doc user module for list of arguments
      user:
        # another way to write = "{{ users['dmarcus']['uname'] }}"
        name: "{{ users.dmarcus.uname }}"
        # another way to write = "{{ users['dmarcus']['fname'] }} {{ users['dmarcus']['lname'] }}"
        comment: "{{ users.dmarcus.fname }} {{ users.dmarcus.lname }}"
        shell: "{{ users.dmarcus.shell }}"
        state: present
...
