---
- name: mariadb packages installed and service running
  hosts: all
  
  tasks:
    - name: install packages
      yum:
        name: "{{ packages }}"
      vars: 
        packages: 
        - mariadb-server
      when: ansible_distribution == "Red Hat" 
      
    - name: start MariaDB service
      service:
        name: mariadb
        state: started
...
