---
- name: mariadb packages installed and service running
  hosts: all
  
  tasks:
    - name: install packages
      yum:
        name: "{{ packages }}"
      vars: 
          packages: 
          - mariadb
          - python3-PyMySQL
      when: ansible_distribution == "Red Hat" 
      
    - name: start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: True
...
