---
- name: line exists in file
  hosts: all
  
  tasks:
    - name: Ensure line exists
      lineinfile:
        path: /tmp/testfile
        line: "dont panic"
        create: yes
      notify: Restart the ssh daemon

  handlers:
    - name: Restart the ssh daemon
      service:
        name: sshd
        state: restarted
...
