---
- name: set file in /etc/sudoers.d with passwordless sudo 
  hosts: all
  become: true
  vars:
    david: david-passwordless-sudo

  tasks:
    - name: create file in /etc/sudoers.d
      file:
        state: touch
        path: /etc/sudoers.d/{{ david }}
        owner: root
        mode: 0400

    - name: set content
      copy:
        content: "david ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/{{ david }}

    - debug:
        msg: "set your ansible.cfg [privilege_escalation] become_ask_pass = false"
...