---
- name: mariadb stopped and packages uninstalled 
  hosts: all
  
  tasks:        
    - name: uninstall packages
      yum:
        name: "{{ packages }}"
        state: removed
      vars: 
          packages: 
          - mariadb
      when: ansible_distribution == "Red Hat" 
...
