---
- name: send public ssh key to managed hosts
  hosts: all

  tasks:
  # A play that ensures that your public key is deployed to the managed hosts' root accounts
    - name: Ensure public ssh key is in roots ~/.ssh/authorized_hosts
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub

  # Because the managed host would not have SSH key-based authentication configured yet, you would have to run the playbook using the ansible-playbook command with the --ask-pass option in order for the command to authenticate as the remote user.